# This file generates the GitHub Actions matrix.
# ZMK Config for hitsuki46 - Zephyr 4.1 with badjeff/zmk-pmw3610-driver
---
include:
 - board: xiao_ble/nrf52840/zmk
   shield: hitsuki46_dongle prospector_adapter
   snippet: studio-rpc-usb-uart
   artifact-name: hitsuki46_dongle
 - board: xiao_ble/nrf52840/zmk
   shield: hitsuki46_R
   artifact-name: hitsuki46_R
 - board: xiao_ble/nrf52840/zmk
   shield: hitsuki46_L
   artifact-name: hitsuki46_L
 - board: xiao_ble/nrf52840/zmk
   shield: settings_reset
   artifact-name: settings_reset
